/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test public void testRollMethod() {
        Library libRollTest = new Library();
        assertEquals("roll method should be array of length 4", 4 , libRollTest.roll(4).length);
        assertFalse("roll method should not be equal to 5",  libRollTest.roll(4).length == 5);
    }

    @Test public void testContainsDuplicatesMethod() {
        Library libContainsDuplicatesTest = new Library();
        assertTrue("ContainsDuplicates method should return true" , libContainsDuplicatesTest.containsDuplicates(new int[] {1,3,3,5}));
        assertFalse("ContainsDuplicates method should return false",  libContainsDuplicatesTest.containsDuplicates(new int[] {1,2,3,5}));
    }

    @Test public void testCalculateAverageMethod() {
        Library libCalculateAverageTest = new Library();
        assertEquals("CalculateAverage method should return", String.valueOf(17.5) , String.valueOf(libCalculateAverageTest.calculateAverage(new int[] {10,15,25,20})));
        assertEquals("CalculateAverage method should return", String.valueOf(0.0) , String.valueOf(libCalculateAverageTest.calculateAverage(new int[] {0,0,0,0})));
    }

    @Test public void testGetLowestAverageArrayMethod() {
        Library libGetLowestAverageArrayTest = new Library();
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int [] expectedArray = new int[]  {55, 54, 60, 53, 59, 57, 61};
        int [] smallestAveragedArray = libGetLowestAverageArrayTest.getLowestAverageArray(weeklyMonthTemperatures);
       for (int i=0; i< smallestAveragedArray.length; i++) {
           assertEquals("GetLowestAverageArray should match the expected array", expectedArray[i] , smallestAveragedArray[i]);
       }

    }

}
